server:
  port: 8085
  servlet:
    context-path: /

rednote:
  doc:
    group: '文件服务'
    package: org.rednote.oss.controller

# Oss配置
oss:
  type: 1 # 0：本地存储, 1：阿里云存储

# 本地文件上传路径
file:
  upload:
    path: xxxxxxxxxxxxxx

aliyun:
  oss:
    endpoint: xxxxxxxxxxxxxxxxxxxxxxxxxx
    access-key-id: xxxxxxxxxxxxxxxxxxxxx
    access-key-secret: xxxxxxxxxxxxxxxxx
    bucket-name: xxxxxxxxxxxxxxxxxxxxxxx